### ISSUE TITLE
Need a way to map Carrier Account Type to Carrier Metadata Name

### ISSUE THREAD

**Issue by bensontrent** [EasyPost/examples#106]
I'm creating a shipping app for a white label version of EasyPost.  I'v created this interface to allow users to set default values for their shipping rates:

![Animation](https://github.com/EasyPost/examples/assets/5982592/cd11dafb-4732-438f-9342-93b30eac9c0b)

This interface is not ideal, since it lists all EasyPost carriers. 

I need a way to map the data from the `/carrier_accounts` endpoint that looks like this:

![image](https://github.com/EasyPost/examples/assets/5982592/1ea29017-3fe4-49e3-a5de-382e938c5008)

...to the data that is returned from the `/carrier/metadata` endpoint looks like this:

![image](https://github.com/EasyPost/examples/assets/5982592/66581dec-b89f-4b49-a9b3-c1217ebaad90)

My goal is to only show a list of carriers active on their account, and allow them to set the default metadata values for that carrier.  As you can see, there's not an identical value in the objects shown above to map the value of 'UpsDapAccount' to 'ups'

Could I get an list of all the of carrier `types` so I could map them to their appropriate carrier metadata classification? For example:

| Carrier Account Type  | Carrier Metadata Name |
| ------------- | ------------- |
| UpsDapAccount  | ups  |

I haven't developed the shipping form yet, but this list will be necessary for that as well.

**Comment by Justintime50** [comment]
Hey there, thanks for writing in! As this question does not pertain to the code in this repository directly but is instead a general question about how our API works, we'd love to get you over to our support team who can assist you further. They can be reached via support@easypost.com and will be able to get those questions answered for you. Best!
