### ISSUE TITLE
Easypost Python examples still using version 7

### ISSUE THREAD

**Issue by gene1wood** [EasyPost/examples#124]
It looks like the examples for Python no longer work because they're using the old Version 7 syntax

Example : https://github.com/EasyPost/examples/blob/036f84ca892e1ca29bb56edc4574fa0e3095a4b4/official/guides/getting-started/python/create_from_address.py

**Comment by Justintime50** [comment]
Hey @gene1wood, thanks for reporting this! We've ensured the docs snippets are up-to-date but it appears we missed a few of the guide snippets. We'll comb through them and get fixes up shortly.
